import type { Tenant } from "./tenants.types";

export const TENANTS_MOCK: Tenant[] = [
  {
    id: "t_school_1",
    type: "SCHOOL",
    name: "Colegio San Martín",
    city: "Santiago",
    country: "Chile",
    status: "ACTIVE",
    plan: "PRO",
    ownerName: "María Soto",
    ownerEmail: "maria@sanmartin.cl",
    metrics: { students: 620, teachers: 38, courses: 54 },
    billing: { currency: "CLP", mrr: 189000, nextInvoiceDate: "2026-03-05" },
    createdAt: "2026-01-20",
  },
  {
    id: "t_school_2",
    type: "SCHOOL",
    name: "Liceo Norte",
    city: "Valparaíso",
    country: "Chile",
    status: "PAST_DUE",
    plan: "BASIC",
    ownerName: "Javier Rojas",
    ownerEmail: "jrojas@liceonorte.cl",
    metrics: { students: 410, teachers: 22, courses: 31 },
    billing: { currency: "CLP", mrr: 99000, nextInvoiceDate: "2026-02-15" },
    createdAt: "2026-02-02",
  },
  {
    id: "t_solo_1",
    type: "SOLO_TEACHER",
    name: "Profesor Particular - Camila Díaz",
    city: "Concepción",
    country: "Chile",
    status: "TRIAL",
    plan: "BASIC",
    ownerName: "Camila Díaz",
    ownerEmail: "camila@gmail.com",
    metrics: { students: 18, teachers: 1, courses: 3 },
    billing: { currency: "CLP", mrr: 19900, nextInvoiceDate: "2026-03-01" },
    createdAt: "2026-02-24",
  },
  {
    id: "t_school_3",
    type: "SCHOOL",
    name: "Colegio Santa Ana",
    city: "La Serena",
    country: "Chile",
    status: "SUSPENDED",
    plan: "PRO",
    ownerName: "Paula Arancibia",
    ownerEmail: "paula@santaana.cl",
    metrics: { students: 780, teachers: 44, courses: 60 },
    billing: { currency: "CLP", mrr: 189000, nextInvoiceDate: "2026-02-10" },
    createdAt: "2025-12-10",
  },
];
